version: "3.9"

services:
    machine1:
        container_name: "manager"
        build:
            context: ./
        privileged: true
        init: true
        volumes:
            - './stack:/stack'
        ports:
            - "9000:9000" # Portainer
            - "8080:8080" # Swarmpit

    machine2:
        container_name: "worker1"
        build:
            context: ./
        privileged: true
        init: true

    machine3:
        container_name: "worker2"
        build:
            context: ./
        privileged: true
        init: true

    machine4:
        container_name: "worker3"
        build:
            context: ./
        privileged: true
        init: true
